print(
    len(
        set(
            map(
                str,
                open(
                    'input.txt',
                    'r',
                    encoding='utf8').read().strip().split()
            )
        )
    )
)
