# Generated by Django 3.0.3 on 2021-03-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='sumbission_date',
            new_name='submission_date',
        ),
    ]
