# Generated by Django 3.0.3 on 2021-03-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20210303_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccination',
            new_name='vaccinations',
        ),
    ]
